-- CreateEnum
CREATE TYPE "PrepaymentPaymentType" AS ENUM ('CHECKIN_PLUS_1_DAY', 'CHECKIN', 'RESERVATION', 'CHECKOUT');

-- AlterTable
ALTER TABLE "Villa"
ADD COLUMN "originalName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "extraCapacity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "salesType" TEXT NOT NULL DEFAULT 'komisyon',
ADD COLUMN "kbsReportable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "onlinePayment" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "b2bSharing" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "showInSearch" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "showInOffer" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "prepaymentPaymentType" "PrepaymentPaymentType" NOT NULL DEFAULT 'CHECKIN_PLUS_1_DAY',
ADD COLUMN "ribbonText1" TEXT NOT NULL DEFAULT '',
ADD COLUMN "ribbonText2" TEXT NOT NULL DEFAULT '';
