export const SURROUNDING_SEED_DATA = [
  {
    slug: "yakin-yerler",
    name: "Yakın Yerler",
    locations: [
      "Marmaris Devlet Hastanesi",
      "Şehir Merkezi",
      "Kalkan Şehir Merkezi",
      "Restaurant",
      "Market",
      "Eczane",
      "ATM",
      "Fethiye Şehir Merkezi",
      "Marina",
    ],
  },
  {
    slug: "ulasim",
    name: "Ulaşım",
    locations: [
      "Marmaris Otogarı",
      "Adnan Menderes Havalimanı",
      "Bodrum Limanı",
      "Toplu Taşıma",
      "Dalaman Havalimanı",
      "Milas-Bodrum Havalimanı",
      "Marmaris Limanı",
      "Taksi Durağı",
      "Otobüs Durağı",
      "Tren İstasyonu",
    ],
  },
  {
    slug: "populer-yerler",
    name: "Popüler Yerler",
    locations: [
      "Kaş Halk Plajı",
      "İnlice Plajı",
      "Kaputaş Plajı",
      "Bodrum Kalesi",
      "Saklıkent Kanyonu",
      "Deniz/Plaj",
      "Kleopatra Plajı",
      "Ölüdeniz Lagünü",
      "Kelebekler Vadisi",
      "Kayaköy",
      "Dalyan İztuzu",
      "Patara Antik Kent",
      "Xanthos Antik Kent",
      "Tlos Antik Kent",
      "Yamaç Paraşütü",
    ],
  },
] as const;
